In [1]:
import numpy as np

In [2]:
# problem 1 : creating a tensor
aTensor = np.array([
    [[23,50],[7,12]],
    [[57,67],[99,43]],
    [[75,21],[57,12]],
    [[87,26],[18,84]]
])
aTensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [11]:
# problem 2 : multiplying two matrices with different shape
#creating 3x3 matrix 
m1 = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98],
])
#creating 1x3 matrix
m2 = np.array([
    [17],[22],[19]
])
#multiplying m1 matrix and m2 matrix
m1@m2

array([[1852],
       [2454],
       [4305]])

In [15]:
#problem 2 : transpose m1  matrix, search determinant for m1 matrix, inverse m1 matrix
print(m1.transpose(),'\n')#transpose m1 matrix
print(np.linalg.det(m1),'\n')#search m1 matrix determinant
print(np.linalg.inv(m1))#inverse m1 matrix

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]] 

131344.0000000002 

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
