In [1]:
import numpy as np

In [5]:
#problem 1
v = np.array([17,22,19]) 
print(v)

[17 22 19]


In [6]:
#problem 2
a = v
b = np.array([10,20,11])
c = np.array([5,12,9])

print(a+b) #a+b
print(b-a) #b-a
print(a.dot(c)) #a dot c
print(a*b) #a * b
print(np.linalg.norm(a)) #norm a
print(a.dot(b))

[27 42 30]
[-7 -2 -8]
520
[170 440 209]
33.67491648096547
819


In [7]:
#problem 3
u = np.array([2,5])
v = np.array([3,1])
res = np.array([u,v])
print(res)

[[2 5]
 [3 1]]
